# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: xxMichalPK/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xxMichalPK
          template: classic
          base: header, activity, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          base_skip: yes
          config_display: columns
          config_timezone: Europe/Warsaw
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_repositories: yes
          plugin_repositories_featured: xxMichalPK/DiskOS, xxMichalPK/MHash
          plugin_repositories_order: featured, pinned, starred, random
